version: '3.5'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ipc: host
    hostname: dynamodb
    ports:
      - 8000:8000
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

  # REACT_APP_FEEDBACK_API is passed at build time in startE2E.sh
  # If running on Linux the value needs to be changed to http://172.17.0.1:3001/feedback
  setup-tables:
    build: dbsetup/.
    image: aws-cli
    volumes:
      - ./.aws/:/root/.aws/
      - ./dbsetup/dynamodbSetupAWS.sh:/dynamodbSetupAWS.sh
    depends_on: 
      - dynamodb
    command: sh dynamodbSetupAWS.sh

  # Update env for linux pipeline/linux REACT_APP_FEEDBACK_API=http://172.17.0.1:3001/feedback
  react-app:
    image: node:14.15.0
    ipc: host
    depends_on: 
      - dynamodb
      - setup-tables
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./frontend/build:/app/build
    command: bash -c "npx http-server build -p 3000"

  # Update env for linux pipeline/linux REACT_APP_FEEDBACK_API=http://172.17.0.1:3001/feedback
  cypress:
    image: cypress/included:6.3.0
    depends_on:
      - react-app
      - dynamodb
    environment:
      - CYPRESS_HOST=http://react-app:3000
    working_dir: /e2e
    volumes:
      - ./frontend/cypress:/e2e/cypress
      - ./frontend/cypress.json:/e2e/cypress.json

networks:
  default:
    external:
      name: feedback-network
