AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Lambda and DynamoDB Feedback App Backend

Mappings:
  envVars:
    values:
      feedbackTableName: feedback

Globals:
  Function:
    Timeout: 30

Resources:
  feedbackFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: feedback/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          FEEDBACK_TABLE_NAME: !FindInMap [envVars, values, feedbackTableName]
      Policies:
        - Statement:
            - Sid: DynamoDbAccessPolicy
              Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:Query
                - dynamodb:DeleteItem
              Resource:
                - !Sub
                  - arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}
                  - { tableName: !FindInMap [envVars, values, feedbackTableName] }
      Events:
        FeedbackPost:
          Type: Api
          Properties:
            Path: /feedback
            Method: POST
        FeedbackOptions:
          Type: Api
          Properties:
            Path: /feedback
            Method: OPTIONS

  feedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: feedback
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
